const lightTokens = [
  "[--background:#ffffff]",
  "[--foreground:#111111]",
  "[--primary:#111111]",
  "[--secondary:#646b75]",
  "[--surface-border:#e9edf2]",
  "[--border:#e3e7ec]",
  "[--card:#ffffff]",
  "[--card-foreground:#111111]",
  "[--muted:#f5f7fa]",
  "[--muted-foreground:#6d7480]",
  "[--accent:#f3f5f8]",
  "[--accent-foreground:#111111]",
  "[--input:#e3e7ec]",
  "[--ring:rgba(17,17,17,0.16)]",
  "[--destructive:#dc2626]",
  "[--paper:#fcfcfd]",
  "[--popover-foreground:#111111]",
  "[--brand:#0ea5e9]",
  "[--brand-soft:#bae6fd]",
  "[--shadow-soft:0_18px_38px_-24px_rgba(15,23,42,0.35)]",
];

const aliasTokens = [
  "[--color-background:var(--background)]",
  "[--color-foreground:var(--foreground)]",
  "[--color-primary:var(--primary)]",
  "[--color-secondary:var(--secondary)]",
  "[--color-border:var(--border)]",
  "[--color-card:var(--card)]",
  "[--color-card-foreground:var(--card-foreground)]",
  "[--color-muted:var(--muted)]",
  "[--color-muted-foreground:var(--muted-foreground)]",
  "[--color-accent:var(--accent)]",
  "[--color-accent-foreground:var(--accent-foreground)]",
  "[--color-input:var(--input)]",
  "[--color-ring:var(--ring)]",
  "[--color-destructive:var(--destructive)]",
  "[--color-paper:var(--paper)]",
  "[--color-popover-foreground:var(--popover-foreground)]",
  "[--color-brand:var(--brand)]",
  "[--color-brand-soft:var(--brand-soft)]",
];

const darkTokens = [
  "dark:[--background:#111111]",
  "dark:[--foreground:#f6f3ec]",
  "dark:[--primary:#f6f3ec]",
  "dark:[--secondary:#cbc6bb]",
  "dark:[--surface-border:#2a2a25]",
  "dark:[--border:#2b2a25]",
  "dark:[--card:#111111]",
  "dark:[--card-foreground:#f6f3ec]",
  "dark:[--muted:#171716]",
  "dark:[--muted-foreground:#9a958a]",
  "dark:[--accent:#1a1a18]",
  "dark:[--accent-foreground:#f6f3ec]",
  "dark:[--input:#2b2a25]",
  "dark:[--ring:rgba(246,243,236,0.18)]",
  "dark:[--destructive:#f87171]",
  "dark:[--paper:#171716]",
  "dark:[--popover-foreground:#f6f3ec]",
  "dark:[--brand:#38bdf8]",
  "dark:[--brand-soft:#0c4a6e]",
  "dark:[--shadow-soft:0_20px_44px_-28px_rgba(0,0,0,0.6)]",
];

export const registryTheme = [
  ...lightTokens,
  ...aliasTokens,
  ...darkTokens,
].join(" ");
